
INSERT INTO PERSON_TABLE(PER_ID,PER_NAME,PER_LOC,PER_BIRTHDATE) VALUES (10001,'Joydeep Chowdhury','Kolkata',sysdate());
INSERT INTO PERSON_TABLE(PER_ID,PER_NAME,PER_LOC,PER_BIRTHDATE) VALUES (10002,'Ankit Bhattacharjee','Kolkata',sysdate());
INSERT INTO PERSON_TABLE(PER_ID,PER_NAME,PER_LOC,PER_BIRTHDATE) VALUES (10003,'Arunabha Gupta','Kolkata',sysdate());