INSERT INTO COURSE_TABLE(COURSE_ID,COURSE_NAME,LAST_UPDATED_DATE,CREATED_DATE) VALUES (10001,'SPRING DATA JPA',sysdate(),sysdate());
INSERT INTO COURSE_TABLE(COURSE_ID,COURSE_NAME,LAST_UPDATED_DATE,CREATED_DATE) VALUES (10003,'SPRING BOOT',sysdate(),sysdate());
INSERT INTO COURSE_TABLE(COURSE_ID,COURSE_NAME,LAST_UPDATED_DATE,CREATED_DATE) VALUES (10004,'SPRING CORE',sysdate(),sysdate());
INSERT INTO COURSE_TABLE(COURSE_ID,COURSE_NAME,LAST_UPDATED_DATE,CREATED_DATE) VALUES (10005,'SPRING SECURITY',sysdate(),sysdate());
INSERT INTO COURSE_TABLE(COURSE_ID,COURSE_NAME,LAST_UPDATED_DATE,CREATED_DATE) VALUES (10006,'SPRING MVC',sysdate(),sysdate());